### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by rgieseke** [hausfath/scrape_global_temps#1]
Hi,

great work, thanks!

For Python 3 an import of `reduce` is necessary it seems, in case someone else runs into the same problem ...

```python
from functools import reduce
```

**Comment by gschivley** [comment]
Agreed, thanks for putting it up!

If @hausfath doesn't mind I might suggest changing this as part of a PR that also sets the download directory in relation to location of the script using `os.path.join`

This could also be addressed by using `pd.concat` rather than `reduce`. Easiest if individual dataframes use year/month as a multi-index before concatenating them. Not going to suggest a code change in PR, just leaving it here as a suggestion for others.
